# PDEs 3 Python Refresher

## Using Numpy Arrays

This notebook is a refresher on using numpy arrays in Python, which we will use extensively in the Partial Differential Equations 3 course.

Numpy arrays are similar to Python lists, but they are more efficient for numerical computations.

In this refresher, we will cover the following topics:
- Creating numpy arrays
- Indexing and slicing
- Array operations

Before we can use numpy, we need to import it. In this course, we will typically do this for you.

In [1]:
import numpy as np # This line gives you access to numpy's functions which you can call using np.<function_name>()

## Section 1: Creating Numpy Arrays

Numpy arrays can be created from lists or using functions such as [`np.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) and [`np.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html).

We can also create numpy arrays with more than one dimension, which will be particualrly useful when solving partial differential equations later in the course.

### Creating a numpy array from a list
You can create a numpy array from a Python list using the [`np.array`](https://numpy.org/doc/stable/reference/generated/numpy.array.html) function. This function takes a list as input and returns a numpy array.


In [2]:
array_from_list = np.array(object = [1, 2, 3, 4, 5])
print(array_from_list)

[1 2 3 4 5]


### Creating a numpy array using arange

A more useful ways to create numpy arrays is by specifying the start and end values of the array, and the step size. This can be done using the [`np.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) function.

In [3]:
array_arange = np.arange(start = 0, stop = 10, step = 2)
print(array_arange)

[0 2 4 6 8]


### Creating a numpy array using linspace
The [`np.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) function generates an array of evenly spaced numbers over a specified range. It takes four main arguments: the start value, the end value, the number of points to generate, and whether to include the end value.
**This is the method we will use most often in this course.**

In [4]:
# Using linspace, including the endpoint
array_linspace = np.linspace(start = 0, stop = 1, num = 5, endpoint = True)
print(array_linspace)

[0.   0.25 0.5  0.75 1.  ]


The example above generates an array of 5 numbers on the interval [0, 1] (including both 0 and 1).

If we set `endpoint = False`, the spacing of the elements in the array is changed accoridngly.
The example below generates an array of 5 numbers on the interval [0, 1) (including 0 but not 1).

In [5]:
# Now excluding the endpoint.
array_linspace = np.linspace(start = 0, stop = 1, num = 5, endpoint = False)
print(array_linspace)

[0.  0.2 0.4 0.6 0.8]


### Using np.zeros

Sometimes, we may want to create an array where values can be input later. One of the easiest ways to do this is to use the [`np.zeros`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) function. This function takes the shape of the array as input and returns an array of zeros with the specified shape.

In [6]:
array_zeros = np.zeros(shape = 5)
print(array_zeros)

[0. 0. 0. 0. 0.]


### 2D Arrays

So far we have looked at 1D numpy arrays. However in this course, we will often work with 2D arrays. Using `np.zeros`, we can create a 2D array by specifying the shape as a tuple. The example below creates a 2D array with 2 rows and 3 columns.

In [7]:
array_2d_zeros = np.zeros(shape = (2, 3))
print(array_2d_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


## Exercises
1. Create a numpy array from the list `[10, 20, 30, 40, 50]`. Print the array.

In [8]:
input_list = [10, 20, 30, 40 , 50]
# Your code here:



2. Create a numpy array containing 4 numbers on the interval [0, 1] (including both 0 and 1) and a second array containing 4 numbers on the interval [0, 1) (including 0 but not 1). Print both arrays.

In [9]:
# Your code here:

3. Create a 2D numpy array of zeros with 3 rows and 4 columns. Print the array.

In [10]:
# Your code here:

## Section 2: Indexing and Slicing

Indexing and slicing numpy arrays allows you to access and modify elements of the array. This is similar to the behaviour used to slice lists in Python.

### Accessing elements
You can access elements of a numpy array using square brackets and the index of the element. **Numpy arrays are zero-indexed, meaning the first element has an index of 0.**

In [33]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
first_element = array[0]
last_element = array[-1]
print(f"First element: {first_element}\nLast element:  {last_element}")

First element: 0
Last element:  9


### Shape of numpy arrays
You can get the shape of a numpy array using the `shape` attribute.

In [26]:
array = np.array([[1, 2, 3], [4, 5, 6]])
shape = array.shape
print(shape)

(2, 3)


### Slicing
You can slice a numpy array to access a range of elements. The syntax for slicing is `array[start:stop:step]`.

In [31]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
slice_1 = array[2:5]  # Elements from index 2 to 4
slice_2 = array[::2]  # Every second element
slice_3 = array[::-1] # Reversed array
print(f"Elements from index 2 to 4:  {slice_1}")
print(f"Every second element:        {slice_2}")
print(f"Reversed array:              {slice_3}")

Elements from index 2 to 4:  [2 3 4]
Every second element:        [0 2 4 6 8]
Reversed array:              [9 8 7 6 5 4 3 2 1 0]


## Exercises
1. Given `array_1` below, extract the elements from index 3 to 7.

In [18]:
array_1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
# Your code here:


2. Reverse `array_2` using slicing.

In [12]:
array_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Your code here:


## Section 3: Array Operations

Numpy arrays support a variety of operations, including element-wise operations, passing arrays into mathematical functions, and using functions like [`np.min`](https://numpy.org/doc/stable/reference/generated/numpy.amin.html), [`np.max`](https://numpy.org/doc/stable/reference/generated/numpy.amax.html) to determine the properties of the elements.

### Element-wise operations
Element-wise operations are performed on each element of the array. These work in a similar way to mathematical operations on scalars.

In [35]:
array = np.array([1, 2, 3, 4, 5])
array_squared = array ** 2
array_plus_10 = array + 10
print(f"Original array: {array}")
print(f"Squared array:  {array_squared}")
print(f"array + 10:     {array_plus_10}")

Original array: [1 2 3 4 5]
Squared array:  [ 1  4  9 16 25]
array + 10:     [11 12 13 14 15]


### Passing arrays into mathematical functions
You can pass numpy arrays into mathematical functions, which will apply the function to each element of the array.
This works for numpy functions like [`np.sin`](https://numpy.org/doc/stable/reference/generated/numpy.sin.html), [`np.cos`](https://numpy.org/doc/stable/reference/generated/numpy.cos.html), and [`np.exp`](https://numpy.org/doc/stable/reference/generated/numpy.exp.html) as well as functions you define yourself which accept floats as input.

In [38]:
array_sin = np.sin(array)
print(f"Original array: {array}")
print(f"sin of array:   {array_sin}")

Original array: [1 2 3 4 5]
sin of array:   [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


### Using np.min and np.max
The [`np.min`](https://numpy.org/doc/stable/reference/generated/numpy.amin.html) and [`np.max`](https://numpy.org/doc/stable/reference/generated/numpy.amax.html) functions return the minimum and maximum values of a numpy array, respectively.

In [21]:
array_min = np.min(array)
array_max = np.max(array)
print(array_min, array_max)

1 5


You may also find the functions [`np.sum`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [`np.mean`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) and [`np.std`](https://numpy.org/doc/stable/reference/generated/numpy.std.html) useful.

## Exercises
1. Given `array_3`, calculate the square of each element.

In [ ]:
array_3 = np.array([5, 10, 15, 20, 25])
# Your code here:


2. Find the minimum and maximum values of the 2D array `array_4`.

In [14]:
array_4 = np.array([[3, 7, 2], [8, 1, 5], [4, 6, 9]])
# Your code here:

**Bonus Question**

3. Find the mean of the 2D array `array_4` along each row.

[Hint: You may find the `axis` argument of the [`np.mean`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) function useful.]

In [39]:
# Your code here: